---
name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      
      - uses: actions/setup-python@v5
      - run: poetry build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Version ${{ github.ref_name }}"
          files: |
            dist/*